### ISSUE TITLE
Type description not showing inside JSX tags

### ISSUE THREAD

**Issue by cj** [neoclide/coc-tsserver#161]
First off - thank you for this amazing plugin!

In the following gif below you'll see it shows the type description outside of a tag, but inside of a JSX tag it is now shown.  It shows for other types, just not TSC, i.e. snippets work just fine.

![CleanShot 2020-06-02 at 23 59 42](https://user-images.githubusercontent.com/1819/83597633-6aac2780-a52d-11ea-84ac-214f29d9501d.gif)

Is there a setting I am missing, or is it a bug?

Please find below my current configs and versions:

<details><summary>:CocInfo</summary>
<p>

## versions

vim version: NVIM v0.5.0-nightly
node version: v10.20.1
coc.nvim version: 0.0.78-4d98f9059c
coc.nivm directory: /Users/cj/.cache/vim/dein/.cache/init.vim/.dein
term: tmux-256color
platform: darwin

## Output channel: git

Looking for git in: git
> git rev-parse --show-toplevel
resolved root: /Users/cj/Documents/apps/**/app
resolved root: /Users/cj/Documents/apps/**/app
> git ls-files -- app/components/App/index.tsx
> git config user.name
resolved root: /Users/cj/Documents/apps/**/app
> git symbolic-ref --short HEAD
> git diff --name-status
> git diff --staged --name-status
> git ls-files --others --exclude-standard
> git --no-pager blame -b -p --root -L18,18 --date relative app/components/App/index.tsx
> git --no-pager show :app/components/App/index.tsx
> git diff /Users/cj/Documents/apps/**/app/app/components/App/index.tsx
resolved root: /Users/cj/Documents/apps/**/app
resolved root: /Users/cj/Documents/apps/**/app
> git symbolic-ref --short HEAD
> git ls-files -- app/components/App/index.tsx
> git diff --name-status
> git diff --staged --name-status
> git ls-files --others --exclude-standard
> git --no-pager show :app/components/App/index.tsx
> git diff /Users/cj/Documents/apps/**/app/app/components/App/index.tsx
> git --no-pager blame -b -p --root -L19,19 --date relative app/components/App/index.tsx
> git --no-pager blame -b -p --root -L18,18 --date relative app/components/App/index.tsx
> git --no-pager blame -b -p --root -L17,17 --date relative app/components/App/index.tsx
> git --no-pager blame -b -p --root -L13,13 --date relative app/components/App/index.tsx
> git --no-pager blame -b -p --root -L12,12 --date relative app/components/App/index.tsx
> git --no-pager blame -b -p --root -L11,11 --date relative app/components/App/index.tsx
> git --no-pager blame -b -p --root -L11,11 --date relative app/components/App/index.tsx
resolved root: /Users/cj/Documents/apps/**/app
resolved root: /Users/cj/Documents/apps/**/app
> git symbolic-ref --short HEAD
> git ls-files -- app/components/App/index.tsx
> git diff --name-status
> git diff --staged --name-status
> git ls-files --others --exclude-standard
> git --no-pager show :app/components/App/index.tsx
> git diff /Users/cj/Documents/apps/**/app/app/components/App/index.tsx
> git --no-pager blame -b -p --root -L11,11 --date relative app/components/App/index.tsx
resolved root: /Users/cj/Documents/apps/**/app
resolved root: /Users/cj/Documents/apps/**/app
> git symbolic-ref --short HEAD
> git ls-files -- app/components/App/index.tsx
> git diff --name-status
> git diff --staged --name-status
> git ls-files --others --exclude-standard
> git --no-pager show :app/components/App/index.tsx
> git diff /Users/cj/Documents/apps/**/app/app/components/App/index.tsx
resolved root: /Users/cj/Documents/apps/**/app
> git ls-files -- app/components/App/index.tsx
> git --no-pager show :app/components/App/index.tsx
> git diff /Users/cj/Documents/apps/**/app/app/components/App/index.tsx
resolved root: /Users/cj/Documents/apps/**/app
> git ls-files -- app/components/App/index.tsx
> git --no-pager show :app/components/App/index.tsx
> git diff /Users/cj/Documents/apps/**/app/app/components/App/index.tsx
resolved root: /Users/cj/Documents/apps/**/app
> git ls-files -- app/components/App/index.tsx
> git --no-pager show :app/components/App/index.tsx
> git diff /Users/cj/Documents/apps/**/app/app/components/App/index.tsx
> git --no-pager blame -b -p --root -L11,11 --date relative app/components/App/index.tsx
> git --no-pager blame -b -p --root -L11,11 --date relative app/components/App/index.tsx
resolved root: /Users/cj/Documents/apps/**/app
> git ls-files -- app/components/App/index.tsx
> git --no-pager show :app/components/App/index.tsx
> git diff /Users/cj/Documents/apps/**/app/app/components/App/index.tsx
> git --no-pager blame -b -p --root -L12,12 --date relative app/components/App/index.tsx
> git --no-pager blame -b -p --root -L12,12 --date relative app/components/App/index.tsx
> git --no-pager blame -b -p --root -L12,12 --date relative app/components/App/index.tsx
> git --no-pager blame -b -p --root -L12,12 --date relative app/components/App/index.tsx
> git --no-pager blame -b -p --root -L12,12 --date relative app/components/App/index.tsx
resolved root: /Users/cj/Documents/apps/**/app
> git ls-files -- app/components/App/index.tsx
> git --no-pager show :app/components/App/index.tsx
> git diff /Users/cj/Documents/apps/**/app/app/components/App/index.tsx
resolved root: /Users/cj/Documents/apps/**/app
> git ls-files -- app/components/App/index.tsx
> git --no-pager show :app/components/App/index.tsx
> git diff /Users/cj/Documents/apps/**/app/app/components/App/index.tsx
resolved root: /Users/cj/Documents/apps/**/app
> git ls-files -- app/components/App/index.tsx
> git --no-pager show :app/components/App/index.tsx
> git diff /Users/cj/Documents/apps/**/app/app/components/App/index.tsx
resolved root: /Users/cj/Documents/apps/**/app
> git ls-files -- app/components/App/index.tsx
> git --no-pager show :app/components/App/index.tsx
> git diff /Users/cj/Documents/apps/**/app/app/components/App/index.tsx
> git --no-pager blame -b -p --root -L12,12 --date relative app/components/App/index.tsx
> git --no-pager blame -b -p --root -L12,12 --date relative app/components/App/index.tsx
resolved root: /Users/cj/Documents/apps/**/app
> git ls-files -- app/components/App/index.tsx
> git --no-pager show :app/components/App/index.tsx
> git diff /Users/cj/Documents/apps/**/app/app/components/App/index.tsx
resolved root: /Users/cj/Documents/apps/**/app
resolved root: /Users/cj/Documents/apps/**/app
> git symbolic-ref --short HEAD
> git ls-files -- app/components/App/index.tsx
> git diff --name-status
> git diff --staged --name-status
> git ls-files --others --exclude-standard
> git --no-pager show :app/components/App/index.tsx
> git diff /Users/cj/Documents/apps/**/app/app/components/App/index.tsx

## Output channel: snippets

[Info 12:09:17 AM] Using ultisnips directories: UltiSnips /Users/cj/.config/coc/ultisnips
[Info 12:09:18 AM] Using ultisnips python command: pyx

## Output channel: highlight

[Info  - 12:09:17 AM] Highlight server running in node v10.20.1

## Output channel: tsserver

[Info  - 12:09:20 AM] Forking TSServer
PATH: /Users/cj/.asdf/installs/nodejs/10.20.1/bin:/Users/cj/.asdf/installs/nodejs/10.20.1/.npm/bin:/usr/local/opt/icu4c/sbin:/usr/local/opt/icu4c/bin:/Users/cj/.asdf/shims:/Users/cj/.asdf/bin:/usr/local/opt/krb5/sbin:/usr/local/opt/krb5/bin:/usr/local/opt/openjdk/bin:./node_modules/.bin:/usr/local/opt/icu4c/sbin:/usr/local/opt/icu4c/bin:/usr/local/opt/python@3.8/bin:/usr/local/opt/sqlite/bin:/usr/local/opt/openssl@1.1/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/cj/.local/share/cargo/bin:/Users/cj/.local/share/krew/bin:/Users/cj/.local/share/python/pyenv/bin:/Users/cj/.local/bin:/opt/X11/bin:/Users/cj/Library/Python/3.7/bin:/Users/cj/Library/Python/2.7/bin:bin:/Users/cj/Library/Android/sdk/tools:/Users/cj/Library/Android/sdk/platform-tools:/Users/cj/.local/lib/node/bin:/Users/cj/.local/lib/ruby/gems/2.6.0/bin:/Users/cj/Library/Android/sdk/emulator:/Users/cj/Library/Android/sdk/tools/bin:/usr/local/lib/python3.8/site-packages:/usr/local/lib/python3.7/site-packages:/Users/cj/.antigen/bundles/robbyrussell/oh-my-zsh/lib:/Users/cj/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/git:/Users/cj/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/command-not-found:/Users/cj/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/docker:/Users/cj/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/history-substring-search:/Users/cj/.antigen/bundles/softmoth/zsh-vim-mode:/Users/cj/.antigen/bundles/zsh-users/zsh-completions:/Users/cj/.antigen/bundles/zsh-users/zsh-autosuggestions:/Users/cj/.antigen/bundles/zsh-users/zsh-syntax-highlighting:/Users/cj/.antigen/bundles/thewtex/tmux-mem-cpu-load:/Users/cj/.antigen/bundles/tmux-plugins/tmux-battery:/Users/cj/.antigen/bundles/denysdovhan/spaceship-prompt 
[Info  - 12:09:20 AM] Started TSServer
{
  "path": "/Users/cj/Documents/apps/**/app/node_modules/typescript/lib",
  "_api": {
    "versionString": "3.9.3",
    "version": "3.9.3"
  }
}

## Output channel: eslint

[Info  - 12:09:20 AM] ESLint server running in node v10.20.1
[Info  - 12:09:22 AM] ESLint library loaded from: /Users/cj/Documents/apps/**/app/node_modules/eslint/lib/api.js

</p>
</details>

<details><summary>coc-settings.json</summary>
<p>

```yaml
{
  "diagnostic-languageserver.enable": false,
  "suggest.triggerAfterInsertEnter": false,
  "suggest.timeout": 8000,
  "suggest.noselect": false,
  "suggest.enablePreview": true,
  "suggest.detailField": "preview",
  "suggest.autoTrigger": "always",
  "suggest.snippetIndicator": "",
  "suggest.maxCompleteItemCount": 30,
  "suggest.echodocSupport": true,
  "typescript.referencesCodeLens.enable": true,
  "typescript.suggest.includeAutomaticOptionalChainCompletions": true,
  "typescript.suggest.enabled": true,
  "typescript.suggest.completeFunctionCalls": true,
  "suggest.completionItemKindLabels": {
    "keyword": "",
    "variable": "",
    "value": "",
    "operator": "Ψ",
    "function": "⨕",
    "reference": "渚",
    "constant": "",
    "method": "",
    "struct": "פּ",
    "class": "",
    "interface": "",
    "text": "♣",
    "enum": "",
    "enumMember": "",
    "module": "",
    "color": "",
    "property": "",
    "field": "",
    "unit": "",
    "event": "鬒",
    "file": "",
    "folder": "",
    "snippet": "",
    "typeParameter": "",
    "default": ""
  },
  "diagnostic.signOffset": 9999999,
  "diagnostic.infoSign": "●",
  "diagnostic.errorSign": "●",
  "diagnostic.warningSign": "●",
  "diagnostic.refreshOnInsertMode": true,
  "git.enableGutters": true,
  "git.branchCharacter": "",
  "git.addGBlameToBufferVar": true,
  "git.virtualTextPrefix": "❯ ",
  "git.addedSign.hlGroup": "GitGutterAdd",
  "git.changedSign.hlGroup": "GitGutterChange",
  "git.removedSign.hlGroup": "GitGutterDelete",
  "git.topRemovedSign.hlGroup": "GitGutterDelete",
  "git.changeRemovedSign.hlGroup": "GitGutterChangeDelete",
  "git.addedSign.text": "▎",
  "git.changedSign.text": "▎",
  "git.removedSign.text": "▏",
  "git.topRemovedSign.text": "▔",
  "git.changeRemovedSign.text": "▋",
  "coc.preferences.snippetStatusText": "Ⓢ ",
  "coc.preferences.formatOnType": false,
  "tsserver.formatOnType": false,
  "tsserver.enable": true,
  "tailwindCSS.headwind.runOnSave": false,
  "coc.preferences.formatOnSaveFiletypes": [
    "ruby",
    "json",
    "typescript",
    "typescriptreact",
    "javascript",
    "javascriptreact",
    "yaml"
  ],
  "typescript.format.enabled": true,
  "javascript.format.enabled": true,
  "prettier.statusItemText": "ⓟ ",
  "prettier.disableSuccessMessage": true,
  "html.filetypes": ["html", "handlebars", "svelte"],
  "emmet.includeLanguages": {
    "vue-html": "html",
    "javascript": "javascriptreact",
    "typescript": "typescriptreact",
    "typescriptreact": "typescriptreact"
  },
  "python.autoComplete.addBrackets": true,
  "eslint.filetypes": [
    "javascript",
    "javascript.jsx",
    "javascriptreact",
    "typescript",
    "typescript.jsx",
    "typescriptreact",
    "vue",
    "svelte",
    "eruby.javascript"
  ],
  "eslint.run": "onSave",
  "eslint.quiet": true,
  "eslint.enable": true,
  "eslint.autoFix": true,
  "eslint.autoFixOnSave": true,
  "prettier.eslintIntegration": true,
  "json.enable": true,
  "json.format.enable": true,
  "solargraph.diagnostics": true,
  "solargraph.autoformat": true,
  "solargraph.formatting": true,
  "solargraph.useBundler": true,
  "solargraph.bundlerPath": "/Users/cj/.asdf/shims/bundle",
  "solargraph.promptDownload": false,
  "solargraph.hover": true,
  "typescript.format.insertSpaceAfterSemicolonInForStatements": false,
  "typescript.suggest.autoImports": true,
  "javascript.suggest.autoImports": true,
  "yaml.format.enable": true,
  "yaml.validate": true,
  "yaml.completion": true,
  "yaml.hover": false,
  "tabnine.priority": 0,
  "diagnostic-languageserver.linters": {
    "ruby": ["rubocop", "reek"],
    "vim": ["vint"]
  },
  "stylelint.enable": false,
  "css.lint.unknownAtRules": "ignore",
  "scss.validate": false,
  "yank.enableCompletion": false
}
```

</p>
</details>

Please let me know if you need any more information!
