### ISSUE TITLE
tsserver dies over and over in a monorepo project

### ISSUE THREAD

**Issue by avahe-kellenberger** [neoclide/coc-tsserver#267]
I'm working in a monorepo with multiple sub-projects that sometimes link to one another.

This is the basic layout:

```yml
central:
  ui:
    node_modules:
      util (symlink)
  services:
    node_modules:
      util (symlink)
  api:
    node_modules:
      services (symlink)
      util (symlink)
  util:
    node_modules
```

I'm not sure what's causing the issue by looking at the logs:
[tsserver.log](https://github.com/neoclide/coc-tsserver/files/6111262/tsserver.log)
[output-tsserver.log](https://github.com/neoclide/coc-tsserver/files/6111267/output-tsserver.log)

I'm thinking there might be a cyclical issue when detecting the project file,
but it's just a guess.

This breaks the entire extension for me.
